"""empty message

Revision ID: 1935b2d16a9a
Revises: 9ca518039518
Create Date: 2018-03-29 04:27:45.592375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1935b2d16a9a'
down_revision = '9ca518039518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charts')
    # ### end Alembic commands ###
