"""add location

Revision ID: 970367203e61
Revises: cda110e4a2b4
Create Date: 2018-02-06 22:51:09.778474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970367203e61'
down_revision = 'cda110e4a2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
