"""empty message

Revision ID: 9ca518039518
Revises: 024221a7f3ba
Create Date: 2018-02-27 11:37:49.874965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca518039518'
down_revision = '024221a7f3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolist', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolist', 'created')
    # ### end Alembic commands ###
