"""empty message

Revision ID: c10b5f73f45d
Revises: 1935b2d16a9a
Create Date: 2018-04-08 17:12:27.654048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10b5f73f45d'
down_revision = '1935b2d16a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('MQ2', sa.Integer(), nullable=True))
    op.add_column('charts', sa.Column('shidu', sa.Integer(), nullable=True))
    op.add_column('charts', sa.Column('wendu', sa.Integer(), nullable=True))
    op.drop_column('charts', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('data', sa.INTEGER(), nullable=True))
    op.drop_column('charts', 'wendu')
    op.drop_column('charts', 'shidu')
    op.drop_column('charts', 'MQ2')
    # ### end Alembic commands ###
